In [1]:
# @ written by shubham bansal:
import pandas as pd
import  numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import DBSCAN
from geopy.distance import great_circle
import pygmaps
from scipy.spatial import ConvexHull
from datetime import datetime
# @ written by shubham bansal:
from haversine import haversine
%matplotlib inline

print('heLlo')

heLlo

In [19]:
data=pd.read_csv('Data_july_1.csv')
S_data=data.sort_values('IST_TIME')
Data_array=S_data.as_matrix()
data.columns
Data_array.shape[0]


# np.where(df[''].map(len) > df['b'].map(len), df['a'].map(len), df['b'].map(len))

4924

In [ ]:
for i  in range (0,Data_array.shape[0]):

s=S_time
Total_day_time=sum(int(i) * 60**index for index, i in enumerate(s.split(":")[::-1]))

In [3]:
S_lat=Data_array[0][1]
S_long=Data_array[0][2]
Start_Acc=Data_array[0][6]
Time=Data_array[0][5]
size=Data_array.shape[0]
Data_Train=pd.DataFrame(columns=['Latitude','Longitude','Acc_distance','Time'])
Data_Train=Data_Train.append({'Latitude':S_lat,'Longitude':S_long,'Acc_distance':Start_Acc,'Time':Time},ignore_index=True)

In [4]:
for i in range(0,1127):
    if abs(Start_Acc-Data_array[i][6]) >=100 :   
         Start_Acc=Data_array[i][6]
         Data_Train=Data_Train.append({'Latitude':Data_array[i][1],'Longitude':Data_array[i][2],'Acc_distance':Start_Acc,'Time':Data_array[i][5]},ignore_index=True)
    else :
        continue

In [5]:
Data_Train

      Latitude  Longitude Acc_distance      Time
0    12.924996  77.592804     12370232  00:22:22
1    12.924743  77.592957     12370341  06:50:07
2    12.924442  77.593544     12370441  07:27:38
3    12.923456  77.593437     12370566  07:27:58
4    12.923175  77.592468     12370674  07:28:38
5    12.923193  77.591499     12370782  07:28:58
6    12.923245  77.590294     12370894  07:29:17
7    12.923261  77.589729     12370998  07:29:27
8    12.923254  77.588509     12371124  07:29:57
9    12.922658  77.588051     12371225  07:30:27
10   12.921780  77.588020     12371327  07:30:47
11   12.921683  77.586876     12371441  07:31:18
12   12.921696  77.585831     12371564  07:31:38
13   12.921147  77.584770     12371684  07:32:08
14   12.919856  77.584747     12371816  07:32:27
15   12.919806  77.584023     12371937  07:32:47
16   12.919817  77.582787     12372043  07:33:17
17   12.919876  77.581787     12372148  07:33:37
18   12.919878  77.580978     12372269  07:33:57
19   12.919875  77.579674     12372380  07:34:27
20   12.919911  77.578484     12372484  07:34:46
21   12.919931  77.577957     12372600  07:34:56
22   12.919971  77.576393     12372729  07:35:26
23   12.919998  77.575333     12372847  07:35:46
24   12.919956  77.574310     12372967  07:36:06
25   12.919140  77.573990     12373091  07:36:26
26   12.918078  77.573601     12373215  07:36:46
27   12.917041  77.573532     12373316  07:37:45
28   12.917331  77.572823     12373416  07:38:26
29   12.917437  77.572769     12373516  07:42:15
..         ...        ...          ...       ...
127  12.863286  77.658577     12385939  08:42:57
128  12.862706  77.659042     12386058  08:43:01
129  12.861141  77.660278     12386275  08:43:11
130  12.859517  77.661575     12386503  08:43:21
131  12.857941  77.662819     12386725  08:43:31
132  12.856443  77.664017     12386957  08:43:42
133  12.855046  77.665123     12387152  08:43:52
134  12.853645  77.666229     12387348  08:44:02
135  12.852235  77.667351     12387545  08:44:12
136  12.850856  77.668434     12387738  08:44:22
137  12.849580  77.669456     12387917  08:44:32
138  12.848389  77.670380     12388082  08:44:42
139  12.847239  77.670830     12388223  08:44:52
140  12.846550  77.669716     12388366  08:45:02
141  12.845964  77.668518     12388511  08:45:12
142  12.845546  77.667465     12388628  08:45:31
143  12.845386  77.666306     12388761  08:46:31
144  12.845382  77.665024     12388867  08:47:51
145  12.845418  77.663727     12388970  08:48:30
146  12.845430  77.663116     12389073  08:48:40
147  12.845404  77.662033     12389185  08:50:05
148  12.845307  77.660957     12389308  08:51:35
149  12.845049  77.660233     12389413  08:51:55
150  12.844198  77.660248     12389513  08:52:15
151  12.843003  77.660332     12389644  08:52:35
152  12.841606  77.660271     12389766  08:53:04
153  12.840920  77.660095     12389877  08:53:14
154  12.839664  77.659782     12390003  08:53:44
155  12.839012  77.658989     12390106  08:54:04
156  12.838386  77.658722     12390207  08:54:34

[157 rows x 4 columns]

In [6]:
Slot_Matrix=Data_Train.as_matrix()

In [7]:
Data_making=pd.read_csv('150218661.csv')

In [22]:
Data_Treatment=Data_making[['LAT','LONGITUDE','IST_TIME','IST_DATE','SPEED_KMPH']].copy()
Data_Treatment=Data_Treatment.drop_duplicates(subset=['LAT','LONGITUDE'], inplace=False)
# ['e'] = p.Series(np.random.randn(sLength), index=df1.index)
# df1['e'] = p.Series(np.random.randn(sLength), index=df1.index)
Data_Treatment['Time_in_sec'] = pd.Series(np.random.randn(Data_Treatment.shape[0]), index=Data_Treatment.index)

In [26]:
# Data_Treatment=Data_making[['LAT','LONGITUDE','IST_TIME','IST_DATE','SPEED_KMPH']].copy()
Data_Treatment
for i in range(0,Data_Treatment.shape[0]):
    s=Data_Treatment.iloc[i][2]
    Total_day_time=sum(int(i) * 60**index for index, i in enumerate(s.split(":")[::-1]))
    Data_Treatment.iloc[i][5]=Total_day_time
Data_Treatment

/home/b/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

            LAT  LONGITUDE  IST_TIME    IST_DATE  SPEED_KMPH  Time_in_sec
0     12.924996  77.592804  00:22:22  2016-07-01           0     1.367916
4     12.925045  77.592834  02:29:45  2016-07-01           0    -1.908202
370   12.924743  77.592957  06:50:07  2016-07-01          17     0.419246
371   12.924821  77.592995  06:50:17  2016-07-01           0    -0.454038
592   12.924951  77.593178  07:26:58  2016-07-01           9     1.591112
593   12.924953  77.593353  07:27:08  2016-07-01           0     0.091928
595   12.924824  77.593590  07:27:28  2016-07-01           6    -0.258257
596   12.924442  77.593544  07:27:38  2016-07-01          12     0.597101
597   12.923960  77.593498  07:27:48  2016-07-01          16     0.035692
598   12.923456  77.593437  07:27:58  2016-07-01          19     0.045352
599   12.923196  77.593407  07:28:08  2016-07-01           7    -1.355734
600   12.923171  77.593239  07:28:18  2016-07-01           8    -1.389476
601   12.923196  77.592934  07:28:28  2016-07-01          14    -0.233229
602   12.923175  77.592468  07:28:38  2016-07-01          18    -0.484250
603   12.923193  77.591499  07:28:58  2016-07-01          14     0.169203
604   12.923261  77.589729  07:29:27  2016-07-01          14     1.137290
605   12.923247  77.589478  07:29:37  2016-07-01           9    -1.910744
606   12.923262  77.589043  07:29:47  2016-07-01          18    -0.944790
607   12.921683  77.586876  07:31:18  2016-07-01          19    -0.442464
608   12.923213  77.588135  07:30:07  2016-07-01           8    -1.548516
609   12.921696  77.585831  07:31:38  2016-07-01          11    -0.110819
610   12.922836  77.588058  07:30:17  2016-07-01           9     1.267966
611   12.922658  77.588051  07:30:27  2016-07-01          11     1.808760
612   12.921711  77.585464  07:31:48  2016-07-01          18     3.009809
613   12.921780  77.588020  07:30:47  2016-07-01           4     0.650296
614   12.921663  77.584862  07:31:58  2016-07-01          19    -0.228776
616   12.919856  77.584747  07:32:27  2016-07-01          16    -0.392339
617   12.919780  77.584480  07:32:37  2016-07-01          13     0.088898
618   12.919803  77.583603  07:32:57  2016-07-01          13    -0.743370
619   12.919809  77.583282  07:33:07  2016-07-01          12    -0.724549
...         ...        ...       ...         ...         ...          ...
3401  12.922364  77.595238  18:56:00  2016-07-01          11    -0.071912
3402  12.922701  77.595253  18:56:10  2016-07-01          12    -1.460685
3403  12.923023  77.595261  18:56:20  2016-07-01           9     1.033827
3404  12.923183  77.595116  18:56:30  2016-07-01          10     0.793060
3405  12.923150  77.594841  18:56:40  2016-07-01          10     0.665163
3406  12.923145  77.594666  18:56:50  2016-07-01           0    -0.156321
3409  12.923169  77.594337  18:57:20  2016-07-01          12    -0.296834
3410  12.923177  77.593948  18:57:29  2016-07-01           8    -0.946720
3411  12.923175  77.593796  18:57:39  2016-07-01           0     0.394845
3412  12.923196  77.593651  18:57:49  2016-07-01           0    -0.365272
3415  12.923442  77.593506  18:58:19  2016-07-01          10     0.212737
3416  12.923800  77.593491  18:58:29  2016-07-01          16    -0.758087
3417  12.924262  77.593498  18:58:39  2016-07-01          19    -0.886592
3418  12.924688  77.593498  18:58:49  2016-07-01          15    -1.277859
3419  12.924951  77.593353  18:59:00  2016-07-01           7     1.591775
3420  12.924945  77.593285  18:59:10  2016-07-01           0    -0.781766
3425  12.924929  77.592987  18:59:59  2016-07-01          10    -0.163919
3426  12.924449  77.592682  19:01:39  2016-07-01           0     0.059482
3427  12.924924  77.592674  19:00:09  2016-07-01           6    -1.154957
3428  12.924840  77.592422  19:00:19  2016-07-01          15    -0.374217
3430  12.924489  77.592529  19:00:29  2016-07-01          12    -0.069188
3458  12.924706  77.593185  19:05:27  2016-07-01           0     1.322871
3472  12.924863  77.593216  19:07:47  2016-07-01           0     0.596775
3484  12.924952  77.593201  19:09:47  2016-07-01           9     0.343840
3485  12.924990  77.593010  19:09:57  2016-07-01           5    -2.025936
3496  12.924893  77.592888  19:11:46  2016-07-01           9    -0.290081
3497  12.924930  77.592575  19:11:56  2016-07-01           7    -0.447940
3498  12.924761  77.592453  19:12:06  2016-07-01          10    -0.853541
3499  12.924719  77.592278  19:12:16  2016-07-01           7     1.375917
3500  12.924724  77.592255  19:12:26  2016-07-01           0    -0.183816

[1202 rows x 6 columns]

In [29]:
Data_Treatment = Data_Treatment.as_matrix()

for i in range(0,Data_Treatment.shape[0]):
    s=Data_Treatment[i][2]
    Total_day_time=sum(int(i) * 60**index for index, i in enumerate(s.split(":")[::-1]))
    Data_Treatment[i][5]=Total_day_time

In [30]:
Data_Treatment

array([[12.924996, 77.592804, '00:22:22', '2016-07-01', 0, 1342],
       [12.925044999999999, 77.592834, '02:29:45', '2016-07-01', 0, 8985],
       [12.924743, 77.592957, '06:50:07', '2016-07-01', 17, 24607],
       ...,
       [12.924761, 77.592453, '19:12:06', '2016-07-01', 10, 69126],
       [12.924719, 77.59227800000002, '19:12:16', '2016-07-01', 7, 69136],
       [12.924724000000001, 77.59225500000002, '19:12:26', '2016-07-01', 0,
        69146]], dtype=object)

In [28]:
import numpy as np
Size1=Data_Treatment.shape[0]
Size1
# count[size-1]=[0]
Slot_matrix_size = Slot_Matrix.shape[0]
count=np.zeros((Slot_matrix_size-1))
speed=np.zeros(Slot_matrix_size-1)
avg = np.zeros(Slot_matrix_size-1)

In [12]:

for i in range(0,Size1):
#     print(i)
    for j in range(1,Slot_matrix_size):
        flag_lat=0;
        flag_long=0;
#         print(j)
#         print(Slot_Matrix[j-1,0], Data_Treatment[i,0],Slot_Matrix[j,0],Data_Treatment[i,0]-Slot_Matrix[j-1,0],Data_Treatment[i,0]-Slot_Matrix[j,0])
#         print(Slot_Matrix[j-1,1],Data_Treatment[i,1],Slot_Matrix[j,1],Data_Treatment[i,1]-Slot_Matrix[j-1,1],Data_Treatment[i,1]-Slot_Matrix[j,1])
        x_lat=Data_Treatment[i,0]-Slot_Matrix[j-1,0]
        y_lat=Data_Treatment[i,0]-Slot_Matrix[j,0]
        x_long=Data_Treatment[i,1]-Slot_Matrix[j-1,1]
        y_long=Data_Treatment[i,1]-Slot_Matrix[j,1]
        if(x_lat>0):
            if(y_lat<0):
                flag_lat=1
#                 print("lat opp mila",x_lat,y_lat)
        if(x_lat<0):
            if(y_lat>0):
                flag_lat=1
#                 print("lat opp mila",x_lat,y_lat)
        
        if(x_long>0):
            if(y_long<0):
                flag_long=1
#                 print("long opp mila",x_long,y_long)
         
        if(x_long<0):
            if(y_long>0):
                flag_long=1
#                 print("long opp mila",x_long,y_long)       
        
#         if ((((Data_Treatment[i][0]- Slot_Matrix[j][0])>0 and (Data_Treatment[i][0]-Slot_Matrix[j-1][0])<0) \
#         or((Data_Treatment[i][0]-Slot_Matrix[j][0])<0 and (Data_Treatment[i][0]-Slot_Matrix[j-1][0])>0))\
#         or\
#         (((Data_Treatment[i][0]-Slot_Matrix[j][0])>0 and (Data_Treatment[i][1]-Slot_Matrix[j-1][1])<0)\
#         or((Data_Treatment[i][0]-Slot_Matrix[j][0])<0 and (Data_Treatment[i][1]-Slot_Matrix[j-1][1])>0))\
#            ):
        #if((((Data_Treatment[i,0]-Slot_Matrix[j-1,0])>0 and (Data_Treatment[i,0]-Slot_Matrix[j,0])<0) or ((Data_Treatment[i,0]-Slot_Matrix[j-1,0])<0 and (Data_Treatment[i,0]-Slot_Matrix[j,0])>0)) or (((Data_Treatment[i,1]-Slot_Matrix[j-1,1])>0 and (Data_Treatment[i,1]-Slot_Matrix[j,1])<0) or ((Data_Treatment[i,1]-Slot_Matrix[j-1,1])<0 and (Data_Treatment[i,1]-Slot_Matrix[j,1])>0))):
    
        if(flag_lat==1 or flag_long==1):
            #print("*************************************************************************************************************************************")
            count[j-1]=count[j-1]+1.0
            speed[j-1]=speed[j-1]+Data_Treatment[i][4]
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            break
count

array([ 18.,  28.,   0.,  16.,   7.,   1.,   0.,  10.,   8.,   2.,   3.,
         6.,  25.,  14.,  13.,  12.,   1.,   3.,  19.,   1.,   4.,   8.,
         5.,   3.,   8.,  33.,  78.,   0.,   0.,   0.,   1.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   2.,   3.,
         4.,   1.,   3.,   0.,  10.,  17.,  21.,  12.,   0.,  13.,  12.,
        15.,   8.,  27.,   5.,  35.,  16.,   4.,   8.,   8.,  33.,  22.,
        21.,   1.,  34.,  46.,  23.,   9.,  11.,   3.,   3.,   0.,  10.,
        18.,  12.,   4.,   5.,   3.,  26.,   9.,   4.,  10.,   3.,   2.,
         3.,   0.,   1.,   3.,   2.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,  48.,  17.,  33.,  75.,  38.,  17.,   9.,
        20.,  18.,  11.,  29.,   9.,   0.,   0.,   0.,   0.,   1.,   0.,
         0.,   0.,   0.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.])

In [16]:
speed

array([ 107.,  246.,    0.,  183.,   96.,    9.,    0.,   74.,   63.,
         21.,   41.,   47.,  229.,  200.,  129.,  147.,   16.,   22.,
        168.,    9.,   58.,   87.,   55.,   36.,  103.,  228.,  660.,
          0.,    0.,    0.,    8.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    4.,   36.,   43.,
         13.,   18.,    0.,  104.,  106.,  134.,  123.,    0.,  103.,
        127.,  121.,   83.,  167.,   29.,  293.,  148.,   29.,   91.,
         67.,  252.,  195.,  118.,   11.,  277.,  374.,  262.,   71.,
        123.,   31.,   32.,    0.,   53.,   81.,  126.,   60.,   63.,
         38.,  160.,   85.,   53.,  109.,   13.,   22.,    8.,    0.,
         10.,   21.,   17.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,  373.,
        191.,  220.,  678.,  501.,  177.,  105.,   99.,  193.,   95.,
        187.,   79.,    0.,    0.,    0.,    0.,    7.,    0.,    0.,
          0.,    0.,    0.,    0.,    8.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.])

In [17]:
for i in range(0, Slot_matrix_size-1):
    if(count[i]==0):
        avg[i] = 0
        continue
    avg[i] = speed[i]/count[i]
    
avg

array([  5.94444444,   8.78571429,   0.        ,  11.4375    ,
        13.71428571,   9.        ,   0.        ,   7.4       ,
         7.875     ,  10.5       ,  13.66666667,   7.83333333,
         9.16      ,  14.28571429,   9.92307692,  12.25      ,
        16.        ,   7.33333333,   8.84210526,   9.        ,
        14.5       ,  10.875     ,  11.        ,  12.        ,
        12.875     ,   6.90909091,   8.46153846,   0.        ,
         0.        ,   0.        ,   8.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   2.        ,  12.        ,
        10.75      ,  13.        ,   6.        ,   0.        ,
        10.4       ,   6.23529412,   6.38095238,  10.25      ,
         0.        ,   7.92307692,  10.58333333,   8.06666667,
        10.375     ,   6.18518519,   5.8       ,   8.37142857,
         9.25      ,   7.25      ,  11.375     ,   8.375     ,
         7.63636364,   8.86363636,   5.61904762,  11.        ,
         8.14705882,   8.13043478,  11.39130435,   7.88888889,
        11.18181818,  10.33333333,  10.66666667,   0.        ,
         5.3       ,   4.5       ,  10.5       ,  15.        ,
        12.6       ,  12.66666667,   6.15384615,   9.44444444,
        13.25      ,  10.9       ,   4.33333333,  11.        ,
         2.66666667,   0.        ,  10.        ,   7.        ,
         8.5       ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   7.77083333,  11.23529412,   6.66666667,
         9.04      ,  13.18421053,  10.41176471,  11.66666667,
         4.95      ,  10.72222222,   8.63636364,   6.44827586,
         8.77777778,   0.        ,   0.        ,   0.        ,
         0.        ,   7.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         8.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ])

In [18]:
Slot_Matrix[12][0],Slot_Matrix[12][1]
Data_Treatment[300][0], Data_Treatment[300][1]

(12.91658, 77.602592)

In [31]:
mymap_1_111=pygmaps.pygmaps(12.91735500,77.62260400,180)
# data=pd.read_csv('Data_july_1.csv')
# lat_long_time=data[['LAT','LONGITUDE','IST_TIME']].copy()
# print(data_with_out.shape[0])
# data_with_out_dupliacte = data_with_out.as_matrix(columns=['LAT','LONGITUDE','Time'])


count=0

for j in range(0,Slot_matrix_size):
#        if( (data_with_out_dupliacte[j][2]>'07:00:00') and (data_with_out_dupliacte[j][2]<'08:30:00') ):
          mymap_1_111.addpoint(Slot_Matrix[j][0],Slot_Matrix[j][1],"#FF0000")


# for i  in range(0,19):     
#     mymap_1_111.addpoint(Data_Treatment[i][0],Data_Treatment[i][1],"#00ffff")




# mymap_1_111.addpoint(Data_Treatment[13][0],Data_Treatment[13][1],)
# mymap_1_111.addpoint(Data_Treatment[13][0],Data_Treatment[13][1],)
# mymap_1_111.addpoint(Data_Treatment[13][0],Data_Treatment[13][1],)





mymap_1_111.draw('a.html')

11.99179996235805

In [ ]:
time2=(Data_Treatment[i][3])
tdelta = abs(datetime.strptime(S_time, FMT) - datetime.strptime(time2, FMT))
#print(tdelta)
time_diff=tdelta.total_seconds()

In [ ]:
import os
root = '/home/b/Desktop/Traffic_prediction/gis_project/Data_route_wise/356_EW/1july'
for subdir, dirnames, filenames in os.walk(root):
    for filename in filenames:
        if filename.endswith('-checkpoint.csv') or filename.startswith('2016'):
            continue
#         print(subdir, filename)
        folders = subdir.split(sep='/')
        newfilename = folders[7]+'_'+folders[8]+'_'+filename
      #  print(os.path.join(subdir,filename),newfilename)
        print(newfilename)
        Load_file(os.path.join(subdir,filename), newfilename)